import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from "@mantine/core";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next";
import { Sidebar } from "@/components/shared/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <NuqsAdapter>
            <div style={{ display: "flex", height: "100vh", overflow: "hidden" }}>
              <Sidebar />
              <div style={{ flex: 1, overflow: "auto" }}>{children}</div>
            </div>
          </NuqsAdapter>
        </MantineProvider>
      </body>
    </html>
  );
}
